name: unit tests
on: [push]
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        run: |
          apt install docker.io
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Quetzal
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.7.5
          poetry_version: 1.0.5
          args: install
