name: unit tests
on: [push]
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test 1
        run: |
          env
          pwd
          ls -latrh .
          touch myfile.txt
      - name: Test 2
        run: |
          pwd
          ls -latrh .
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          poetry install
      - name: Run tests
        run: |
          pytest -o log_cli=true -o log_cli_level=DEBUG
      # - name: Install
      #   uses: abatilo/actions-poetry@v1.5.0
      #   with:
      #     python_version: 3.7.7
      #     poetry_version: 1.0.5
      #     args: install
      # - name: Test with pytest
      #   uses: abatilo/actions-poetry@v1.5.0
      #   with:
      #     python_version: 3.7.7
      #     poetry_version: 1.0.5
      #     args: run python -m pytest -o log_cli=true -o log_cli_level=DEBUG
      # - name: Test 3
      #   run: |
      #     pwd
      #     ls -latrh .
